name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/ramidoz.pem
          chmod 400 ~/.ssh/ramidoz.pem
          ssh-keyscan -H 3.139.84.151 >> ~/.ssh/known_hosts

      - name: SSH into AWS and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ramidoz.pem ec2-user@3.139.84.151 << 'EOF'
          cd "/home/ec2-user/Customer Engagement analysis"
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart flaskapp
          EOF